apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "opslevel-sync.fullname" . }}
  labels:
    {{- include "opslevel-sync.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: "{{ .Values.sync.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ include "opslevel-sync.serviceAccountName" . }}
          initContainers:
            {{- with .Values.additionalInitContainers }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            args:
              - service
              - import
              {{- with .Values.sync.args }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- if .Values.apitokenPath }}
              - --api-token-path
              - {{ .Values.apitokenPath }}
              {{- end }}
            envFrom:
            {{- if not .Values.apitokenPath }}
            - secretRef:
                name: {{ .Values.apitokenSecret.name }}
                optional: true
            {{- end }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            volumeMounts:
            - name: config
              mountPath: /app
            {{- with .Values.additionalVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumes:
          - name: config
            configMap:
              name: {{ template "opslevel-sync.fullname" . }}
          {{- with .Values.additionalVolumes }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
