apiVersion: v2
name: kubernetes-sync
type: application
version: 0.5.1
appVersion: "0.6.6"
description: An agent for syncronizing Kubernetes data with OpsLevel
keywords:
- monitoring
- alerting
- metric
home: https://www.opslevel.com/
icon: https://www.opslevel.com/images/OpsLevelLogoText.svg
sources:
- https://github.com/OpsLevel/kubectl-opslevel
maintainers:
- name: OpsLevel
  email: support@opslevel.com
